Hotfix: jbake fails with undefined method start_with? (#81)
Verified.

Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
    at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:341)
    at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:448)
    at org.jbake.parser.AsciidoctorEngine.processAsciiDoc(AsciidoctorEngine.java:141)